package com.local.multiplatformdownloader

import com.local.multiplatformdownloader.core.network.BilibiliRequestProfile
import com.local.multiplatformdownloader.core.network.OkHttpParserClient
import com.local.multiplatformdownloader.core.network.ParserHttpClient
import com.local.multiplatformdownloader.core.network.ParserHttpResponse
import com.local.multiplatformdownloader.feature.creator.CreatorSourceException
import com.local.multiplatformdownloader.platform.bilibili.BilibiliCreatorSource
import com.local.multiplatformdownloader.platform.bilibili.BilibiliWbi
import com.local.multiplatformdownloader.platform.bilibili.bilibiliCreatorUid
import com.local.multiplatformdownloader.platform.bilibili.bilibiliIpLocation


import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test
import org.junit.Assume.assumeTrue
import java.net.URI

class BilibiliCreatorSourceTest {
    @Test fun sharedShortLinkResolvesMobileHomepageWithoutSendingCookies() {
        val fake = Fake()
        fake.redirect = "https://m.bilibili.com/space/123?share_from=space"
        val profile = BilibiliCreatorSource(fake).resolve(
            "【无烬映画的个人空间-哔哩哔哩】 https://b23.tv/LUEVHzA", "SESSDATA=test", null)
        assertEquals("123", profile.stableId)
        assertEquals(1, fake.shortRequests)
    }

    @Test fun shortLinksCanFollowRelativeHops() {
        val fake = Fake()
        fake.redirect = "/second"
        val profile = BilibiliCreatorSource(fake).resolve("http://b23.tv/first", "", null)
        assertEquals("123", profile.stableId)
        assertEquals(2, fake.shortRequests)
    }

    @Test fun shortLinksRejectVideoAndUntrustedDestinationsWithoutFetchingThem() {
        for (target in listOf("https://www.bilibili.com/video/BV1vobn6dEAR",
            "https://evil.test/123", "https://space.bilibili.com.evil.test/123",
            "https://user@b23.tv/next", "https://b23.tv:8000/next")) {
            val fake = Fake().apply { redirect = target }
            assertEquals("AUTHOR_QUERY_UNSUPPORTED", assertThrows(CreatorSourceException::class.java) {
                BilibiliCreatorSource(fake).resolve("https://b23.tv/test", "", null)
            }.code)
            assertEquals(1, fake.shortRequests)
            assertEquals(0, fake.navCount)
        }
    }

    @Test fun shortLinkLoopAndMissingRedirectAreReported() {
        for (target in listOf("https://b23.tv/test", "")) {
            val fake = Fake().apply { redirect = target }
            assertEquals("URL_RESOLVE_FAILED", assertThrows(CreatorSourceException::class.java) {
                BilibiliCreatorSource(fake).resolve("https://b23.tv/test", "", null)
            }.code)
            assertEquals(1, fake.shortRequests)
        }
    }

    @Test fun shortLinkRateLimitStopsFurtherRequests() {
        val fake = Fake().apply { shortStatus = 429 }
        val source = BilibiliCreatorSource(fake)
        repeat(2) {
            assertEquals("AUTH_OR_RISK", assertThrows(CreatorSourceException::class.java) {
                source.resolve("https://b23.tv/test", "", null)
            }.code)
        }
        assertEquals(1, fake.shortRequests)
    }

    @Test fun uidAndHomepageValidation() {
        assertEquals("123", bilibiliCreatorUid("UID:123"))
        assertEquals("123", bilibiliCreatorUid("https://space.bilibili.com/123/video?from=share"))
        assertEquals("123", bilibiliCreatorUid("https://m.bilibili.com/space/123"))
        for (bad in listOf("0", "-1", "https://space.bilibili.com.evil.test/123", "https://user@space.bilibili.com/123", "https://space.bilibili.com:8000/123")) {
            assertThrows(CreatorSourceException::class.java) { bilibiliCreatorUid(bad) }
        }
    }

    @Test fun wbiKnownProtocolVector() {
        val key = BilibiliWbi.key("https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png",
            "https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png")
        assertEquals("ea1db124af3c7062474693fa704f4ff8", key)
        // Expected digest independently checked with OpenSSL, not generated by the subject.
        assertEquals("bar=514&baz=1919810&foo=114&wts=1702204169&w_rid=6149fdadf571698ca7e6a567265cd0ee",
            BilibiliWbi.query(mapOf("foo" to "114", "bar" to "514", "baz" to "1919810"), key, 1702204169))
    }

    @Test fun profileAndPaginationUseBVAsWorkIdentity() {
        val fake = Fake()
        val source = BilibiliCreatorSource(fake)
        val profile = source.resolve("123", "", null)
        assertEquals("作者", profile.nickname)
        assertEquals("广东", profile.location)
        assertEquals("99", profile.metrics.first { it.label == "粉丝" }.value)
        val page = source.fetchPage(profile, "", 1, "", null)
        assertEquals("BV1vobn6dEAR", page.works.single().contentId)
        assertEquals(65000L, page.works.single().durationMs)
        assertEquals("2", page.nextCursor)
        assertTrue(page.hasMore)
        assertEquals(1, fake.navCount)
        assertThrows(CreatorSourceException::class.java) { source.fetchPage(profile, "2", 1, "", null) }
        fake.risk = true
        assertEquals("AUTH_OR_RISK", assertThrows(CreatorSourceException::class.java) {
            source.fetchPage(profile, "2", 2, "", null)
        }.code)
    }

    @Test fun ipLocationPrefersNestedProfileAndSupportsLegacyShape() {
        assertEquals(
            "上海",
            bilibiliIpLocation(JSONObject("""{"profile":{"ip_location":"IP属地：上海"},"ip_location":"旧值"}""")),
        )
        assertEquals("旧值", bilibiliIpLocation(JSONObject("""{"ip_location":"旧值"}""")))
        assertEquals("", bilibiliIpLocation(JSONObject()))
    }

    @Test fun emptyOrMalformedListMustNotHideExistingWorks() {
        val fake = Fake()
        val source = BilibiliCreatorSource(fake)
        val profile = source.resolve("123", "", null)
        fake.empty = true
        assertEquals("RESPONSE_CHANGED", assertThrows(CreatorSourceException::class.java) {
            source.fetchPage(profile, "", 1, "", null)
        }.code)
    }

    @Test fun liveCreatorOfUserProvidedSample() {
        assumeTrue(System.getenv("BILIBILI_CREATOR_SMOKE") == "1")
        val http = OkHttpParserClient()
        val metadata = http.getWithoutRedirects("https://api.bilibili.com/x/web-interface/view?bvid=BV1vobn6dEAR",
            BilibiliRequestProfile.apiHeaders, "", 15)
        val data = JSONObject(metadata.body).getJSONObject("data")
        val uid = data.getJSONObject("owner").optString("mid")
        val source = BilibiliCreatorSource(http)
        try {
            val profile = source.resolve(uid, "", null)
            println("BILI_CREATOR_PROFILE uid=$uid namePresent=${profile.nickname.isNotEmpty()} avatarPresent=${profile.avatarUrl.isNotEmpty()} metrics=${profile.metrics.size}")
            val page = source.fetchPage(profile, "", 1, "", null)
            println("BILI_CREATOR_PAGE count=${page.works.size} more=${page.hasMore}")
            assertTrue(page.works.isNotEmpty())
        } catch (e: CreatorSourceException) {
            println("BILI_CREATOR_STOP code=${e.code} message=${e.message}")
            throw e
        }
    }

    private class Fake : ParserHttpClient {
        var redirect = "https://space.bilibili.com/123"
        var shortRequests = 0
        var shortStatus = 302
        var navCount = 0
        var risk = false
        var empty = false
        override fun getWithoutRedirects(url: String, headers: Map<String,String>, cookieHeader: String, timeoutSeconds: Long): ParserHttpResponse {
            if (URI(url).host == "b23.tv") {
                assertEquals("", cookieHeader)
                assertEquals("https", URI(url).scheme)
                shortRequests++
                val target = if (URI(url).path == "/second") "https://space.bilibili.com/123" else redirect
                return ParserHttpResponse(shortStatus, url, emptyList(), "", mapOf("location" to target))
            }
            val path = URI(url).path
            val data = when (path) {
                "/x/web-interface/nav" -> {
                    navCount++
                    """{"wbi_img":{"img_url":"https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png","sub_url":"https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png"}}"""
                }
                "/x/space/wbi/acc/info" -> """{"mid":123,"name":"作者","face":"https://i0.hdslb.com/a.jpg","sign":"简介","level":6,"profile":{"ip_location":"IP属地：广东"}}"""
                "/x/relation/stat" -> """{"follower":99,"following":2}"""
                "/x/space/wbi/arc/search" -> {
                    assertTrue(url.contains("w_rid="))
                    if (empty) """{"list":{"vlist":[]},"page":{"count":25}}""" else
                    """{"list":{"vlist":[{"bvid":"BV1vobn6dEAR","mid":123,"title":"视频","length":"1:05"}]},"page":{"count":25}}"""
                }
                else -> error("Unexpected endpoint")
            }
            return ParserHttpResponse(if (risk) 429 else 200, url, emptyList(), "{\"code\":0,\"data\":$data}", emptyMap())
        }
        override fun get(url: String, headers: Map<String,String>, cookieHeader: String, timeoutSeconds: Long) = error("Redirecting requests forbidden")
        override fun probeContentLength(url: String, headers: Map<String,String>, timeoutSeconds: Long): Long = error("Not needed")
    }
}
